server:
  port: 8082

spring:
  application:
    name: card-service
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:5432/srll_cards
    username: ${DB_USER:srll}
    password: ${DB_PASS:srll_pass}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  data:
    mongodb:
      uri: mongodb://${MONGO_HOST:localhost}:27017/srll_cards
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP:localhost:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

jwt:
  secret: ${JWT_SECRET:c3ByaW5nLWJvb3Qtc3BhY2VkLXJlcGV0aXRpb24tc2VjcmV0LWtleS0yMDI0}
